# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RSACipher(object):
    def setupUi(self, RSACipher):
        RSACipher.setObjectName("RSACipher")
        RSACipher.resize(720, 480)
        self.centralwidget = QtWidgets.QWidget(RSACipher)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(240, 20, 160, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.generateKeysBtn = QtWidgets.QPushButton(self.centralwidget)
        self.generateKeysBtn.setGeometry(QtCore.QRect(460, 20, 120, 35))
        self.generateKeysBtn.setObjectName("generateKeysBtn")
        self.plainTextLabel = QtWidgets.QLabel(self.centralwidget)
        self.plainTextLabel.setGeometry(QtCore.QRect(30, 80, 80, 20))
        self.plainTextLabel.setObjectName("plainTextLabel")
        self.plainTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(110, 80, 250, 100))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.cipherTextLabel = QtWidgets.QLabel(self.centralwidget)
        self.cipherTextLabel.setGeometry(QtCore.QRect(30, 200, 80, 20))
        self.cipherTextLabel.setObjectName("cipherTextLabel")
        self.cipherTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.cipherTextEdit.setGeometry(QtCore.QRect(110, 200, 250, 100))
        self.cipherTextEdit.setObjectName("cipherTextEdit")
        self.encryptBtn = QtWidgets.QPushButton(self.centralwidget)
        self.encryptBtn.setGeometry(QtCore.QRect(130, 330, 90, 30))
        self.encryptBtn.setObjectName("encryptBtn")
        self.decryptBtn = QtWidgets.QPushButton(self.centralwidget)
        self.decryptBtn.setGeometry(QtCore.QRect(240, 330, 90, 30))
        self.decryptBtn.setObjectName("decryptBtn")
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setGeometry(QtCore.QRect(390, 80, 100, 20))
        self.infoLabel.setObjectName("infoLabel")
        self.infoEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.infoEdit.setGeometry(QtCore.QRect(459, 80, 231, 100))
        # Đã bỏ setReadOnly(True) để có thể nhập liệu
        self.infoEdit.setObjectName("infoEdit")
        self.signatureLabel = QtWidgets.QLabel(self.centralwidget)
        self.signatureLabel.setGeometry(QtCore.QRect(390, 200, 100, 20))
        self.signatureLabel.setObjectName("signatureLabel")
        self.signatureEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.signatureEdit.setGeometry(QtCore.QRect(459, 200, 231, 100))
        self.signatureEdit.setReadOnly(True)
        self.signatureEdit.setObjectName("signatureEdit")
        self.signBtn = QtWidgets.QPushButton(self.centralwidget)
        self.signBtn.setGeometry(QtCore.QRect(460, 330, 90, 30))
        self.signBtn.setObjectName("signBtn")
        self.verifyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.verifyBtn.setGeometry(QtCore.QRect(600, 330, 90, 30))
        self.verifyBtn.setObjectName("verifyBtn")
        RSACipher.setCentralWidget(self.centralwidget)

        self.retranslateUi(RSACipher)
        QtCore.QMetaObject.connectSlotsByName(RSACipher)

    def retranslateUi(self, RSACipher):
        _translate = QtCore.QCoreApplication.translate
        RSACipher.setWindowTitle(_translate("RSACipher", "RSA Cipher"))
        self.titleLabel.setText(_translate("RSACipher", "RSA CIPHER"))
        self.generateKeysBtn.setText(_translate("RSACipher", "Generate Keys"))
        self.plainTextLabel.setText(_translate("RSACipher", "Plain Text:"))
        self.cipherTextLabel.setText(_translate("RSACipher", "CipherText:"))
        self.encryptBtn.setText(_translate("RSACipher", "Encrypt"))
        self.decryptBtn.setText(_translate("RSACipher", "Decrypt"))
        self.infoLabel.setText(_translate("RSACipher", "Information:"))
        self.signatureLabel.setText(_translate("RSACipher", "Signature:"))
        self.signBtn.setText(_translate("RSACipher", "Sign"))
        self.verifyBtn.setText(_translate("RSACipher", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RSACipher = QtWidgets.QMainWindow()
    ui = Ui_RSACipher()
    ui.setupUi(RSACipher)
    RSACipher.show()
    sys.exit(app.exec_())